### ISSUE TITLE
启动镜像时报错：ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes]

### ISSUE THREAD

**Issue by voyager0003** [percent4/ES_Learning#1]
1、什么问题：
运行docker compose up时报错，无法启动

2、如何复现：
本地运行路径下的文件结构：
```
❯ tree
.
├── common
│   ├── __init__.py
│   └── llm_chat_api.py
├── config
│   ├── basic_config.yml
│   ├── config_parser.py
│   ├── __init__.py
│   └── model_config.yml
├── data_process
│   ├── data_processor.py
│   ├── file_parser.py
│   └── __init__.py
├── docker-compose.yml
├── docs
│   ├── docker-compose-es.yml
│   ├── docker-compose-milvus.yml
│   └── model_serving.md
├── es
│   ├── data
│   └── plugins
├── files
│   ├── dengyue.txt
```
```
❯ docker compose up
[+] Building 0.0s (0/0)                                                                                                                      docker:default
WARN[0000] Found orphan containers ([kibana-7.17.0]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Running 1/0
 ✔ Container elasticsearch-7.17.0  Created                                                                                                             0.0s 
Attaching to elasticsearch-7.17.0
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:53,599Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "version[7.17.0], pid[7], build[default/docker/bee86328705acaa9a6daede7140defd4d9ec56bd/2022-01-28T08:36:04.875279988Z], OS[Linux/5.15.0-76-generic/amd64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/17.0.1/17.0.1+12]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:53,601Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "JVM home [/usr/share/elasticsearch/jdk], using bundled JDK [true]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:53,601Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=ALL-UNNAMED, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp/elasticsearch-2668874522874534820, -XX:+HeapDumpOnOutOfMemoryError, -XX:+ExitOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Des.cgroups.hierarchy.override=/, -Xms1024m, -Xmx1024m, -XX:MaxDirectMemorySize=536870912, -XX:G1HeapRegionSize=4m, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=15, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker, -Des.bundled_jdk=true]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,632Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [aggs-matrix-stats]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,632Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [analysis-common]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,632Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [constant-keyword]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,632Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [frozen-indices]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,632Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [ingest-common]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,632Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [ingest-geoip]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,632Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [ingest-user-agent]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,632Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [kibana]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,632Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [lang-expression]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,632Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [lang-mustache]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,632Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [lang-painless]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,633Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [legacy-geo]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,633Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [mapper-extras]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,633Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [mapper-version]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,633Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [parent-join]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,633Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [percolator]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,633Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [rank-eval]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,633Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [reindex]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,633Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [repositories-metering-api]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,633Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [repository-encrypted]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,633Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [repository-url]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,633Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [runtime-fields-common]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,633Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [search-business-rules]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,634Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [searchable-snapshots]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,634Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [snapshot-repo-test-kit]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,634Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [spatial]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,634Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [transform]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,634Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [transport-netty4]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,634Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [unsigned-long]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,634Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [vector-tile]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,634Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [vectors]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,634Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [wildcard]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,634Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-aggregate-metric]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,634Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-analytics]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,634Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-async]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,634Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-async-search]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,634Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-autoscaling]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,635Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-ccr]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,635Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-core]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,635Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-data-streams]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,635Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-deprecation]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,635Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-enrich]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,635Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-eql]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,635Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-fleet]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,635Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-graph]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,635Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-identity-provider]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,635Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-ilm]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,635Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-logstash]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,635Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-ml]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,636Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-monitoring]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,636Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-ql]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,636Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-rollup]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,636Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-security]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,636Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-shutdown]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,636Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-sql]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,636Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-stack]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,636Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-text-structure]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,636Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-voting-only-node]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,636Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "loaded module [x-pack-watcher]" }
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,636Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "no plugins loaded" }
elasticsearch-7.17.0  | uncaught exception in thread [main]
elasticsearch-7.17.0  | {"type": "server", "timestamp": "2023-09-22T10:02:54,667Z", "level": "ERROR", "component": "o.e.b.ElasticsearchUncaughtExceptionHandler", "cluster.name": "cluster_elasticsearch", "node.name": "elastic01", "message": "uncaught exception in thread [main]", 
elasticsearch-7.17.0  | "stacktrace": ["org.elasticsearch.bootstrap.StartupException: ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];",
elasticsearch-7.17.0  | "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:157) ~[elasticsearch-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77) ~[elasticsearch-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112) ~[elasticsearch-cli-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "at org.elasticsearch.cli.Command.main(Command.java:77) ~[elasticsearch-cli-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:122) ~[elasticsearch-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80) ~[elasticsearch-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "Caused by: org.elasticsearch.ElasticsearchException: failed to bind service",
elasticsearch-7.17.0  | "at org.elasticsearch.node.Node.<init>(Node.java:1092) ~[elasticsearch-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "at org.elasticsearch.node.Node.<init>(Node.java:309) ~[elasticsearch-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234) ~[elasticsearch-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234) ~[elasticsearch-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434) ~[elasticsearch-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166) ~[elasticsearch-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "... 6 more",
elasticsearch-7.17.0  | "Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes",
elasticsearch-7.17.0  | "at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]",
elasticsearch-7.17.0  | "at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]",
elasticsearch-7.17.0  | "at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]",
elasticsearch-7.17.0  | "at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:398) ~[?:?]",
elasticsearch-7.17.0  | "at java.nio.file.Files.createDirectory(Files.java:700) ~[?:?]",
elasticsearch-7.17.0  | "at java.nio.file.Files.createAndCheckIsDirectory(Files.java:807) ~[?:?]",
elasticsearch-7.17.0  | "at java.nio.file.Files.createDirectories(Files.java:793) ~[?:?]",
elasticsearch-7.17.0  | "at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:300) ~[elasticsearch-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:224) ~[elasticsearch-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:298) ~[elasticsearch-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "at org.elasticsearch.node.Node.<init>(Node.java:429) ~[elasticsearch-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "at org.elasticsearch.node.Node.<init>(Node.java:309) ~[elasticsearch-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234) ~[elasticsearch-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234) ~[elasticsearch-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434) ~[elasticsearch-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166) ~[elasticsearch-7.17.0.jar:7.17.0]",
elasticsearch-7.17.0  | "... 6 more"] }
elasticsearch-7.17.0  | ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];
elasticsearch-7.17.0  | Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
elasticsearch-7.17.0  |         at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
elasticsearch-7.17.0  |         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
elasticsearch-7.17.0  |         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
elasticsearch-7.17.0  |         at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:398)
elasticsearch-7.17.0  |         at java.base/java.nio.file.Files.createDirectory(Files.java:700)
elasticsearch-7.17.0  |         at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
elasticsearch-7.17.0  |         at java.base/java.nio.file.Files.createDirectories(Files.java:793)
elasticsearch-7.17.0  |         at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:300)
elasticsearch-7.17.0  |         at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:224)
elasticsearch-7.17.0  |         at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:298)
elasticsearch-7.17.0  |         at org.elasticsearch.node.Node.<init>(Node.java:429)
elasticsearch-7.17.0  |         at org.elasticsearch.node.Node.<init>(Node.java:309)
elasticsearch-7.17.0  |         at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234)
elasticsearch-7.17.0  |         at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234)
elasticsearch-7.17.0  |         at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434)
elasticsearch-7.17.0  |         at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166)
elasticsearch-7.17.0  |         at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:157)
elasticsearch-7.17.0  |         at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77)
elasticsearch-7.17.0  |         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
elasticsearch-7.17.0  |         at org.elasticsearch.cli.Command.main(Command.java:77)
elasticsearch-7.17.0  |         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:122)
elasticsearch-7.17.0  |         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80)
elasticsearch-7.17.0  | For complete error details, refer to the log at /usr/share/elasticsearch/logs/cluster_elasticsearch.log
elasticsearch-7.17.0 exited with code 1
```

**Comment by voyager0003** [comment]
已解决。具体步骤：
1. 第一次启动，`docker compose up` ，让镜像创建./es目录；
2. 在宿主机上执行 `chmod 777 -R ./es` ，
3. 再次`docker compose up` 就行了
